export const CHECKLIST_QUESTIONS = [
  "Má každá podstránka správne nastavené nadpisy?",
  "Majú správne nastavené nadpisy archív a položky v archíve (články)?",
  "Máme SEO plugin nastavený a vyplnené Title + Meta Description?",
  "Máme vyplnené OG (FB) tagy + automatické generovanie pre články? Vrátane share image 1200×630.",
  "Máme share texty a img aj pre Twitter/LinkedIn?",
  "Máme meta robots a robots.txt – správne nastavené?",
  "Máme sitemap.xml? (Aj pre každú jazykovú mutáciu.)",
  "Máme nastavený tracking (GTM, GA, FB pixel)?",
  "Ak je to e-shop – pokročilá analytika (add_to_cart, purchase, view_item, …)?",
  "Aký je cieľ webu (KPI)? Vieme ho merať a máme naň event?",
  "Máme nastavenú cookie lištu? Naozaj blokuje cookies pred consentom?",
  "Favicon a všetky veľkosti? (realfavicongenerator.net)",
  "Zabezpečený admin prístup a vytvorené prístupy pre klienta?",
  "Máme prístup na produkčný server (FTP/DB)?",
  "Vypnutý basic auth na produkcii?",
  "Vytvorený SSL certifikát na produkcii?",
  "Skontrolované veľkosti obrázkov + automatické zmenšovanie?",
  "Optimalizácia obrázkov na webp / avif?",
  "Cachovanie stránky?",
  "Cloudflare?",
  "Uptimerobot monitoring?",
  "Wordfence (ak WP)?",
  "GTmetrix – rýchlosť?",
  "seo-servis.cz – základné SEO?",
  "Preklápanie webu – pripravené 301 redirecty?",
  "Pridaná Google Search Console?",
];
